#!/bin/sh
############### still a WIP ###############
mode=${1:-full}

# Always run relative to the repository root, no matter where the script is
# invoked from.
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$script_dir" || exit 1

rm -f -r src/*.o src/*.so */*~ *~ src/itks src/itkb
rm -f -r src/*.o-*
rm -f -r src/*.gcno
rm -f -r src/*.gcda
rm -f -r src/antb
rm -f src/Makevars
rm -f src/ants/CITATION.bib
rm -f ants/CITATION.bib
rm -f src/*.a
rm -f src/antb/ANTS-build/Examples/lib*.a
rm -f antb/ANTS-build/Examples/lib*.a

cd inst/include
mv README.md RcppANTsR.h antscore.h RcppANTsR/ ../ && rm -rf * && mv ../README.md ../RcppANTsR.h ../antscore.h ../RcppANTsR ./
cd ../../
