#!/bin/sh
############### still a WIP ###############
mode=${1:-full}

# Always run relative to the repository root, no matter where the script is
# invoked from.
script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$script_dir" || exit 1

rm -f -r src/*.o src/*.so */*~ *~ src/itks src/itkb
rm -f -r src/*.o-*
rm -f -r src/*.gcno
rm -f -r src/*.gcda

if [ "$mode" != "postbuild" ]; then
  rm -f -r src/ants src/antb ants
  rm -f src/Makevars
fi

cd inst/include
mv README.md RcppANTsR.h antscore.h RcppANTsR/ ../ && rm -rf * && mv ../README.md ../RcppANTsR.h ../antscore.h ../RcppANTsR ./
cd ../../
